drop table if exists ml_basketball_full;
drop table if exists ml_basketball_train;
drop table if exists ml_basketball_predict;
create table ml_basketball_train as 
SELECT quote_ident(player_name) as player_name, gs , mp, fg, fga, fg_pct, game_three_made, game_three_att, game_three_perc, ft, fta, ft_pct, orb, drb, trb, ast, stl, blk, tov, pf, pts * 1.0 as pts, game_score, plus_minus, quote_ident(season) as season, date_game, team_age, team_fg, team_fga, team_gtm, team_gta, team_turnovers, team_orb, team_drb, team_trb, team_ft, team_ft_att, team_pf, opp_age, opp_fg, opp_fga, opp_gtm, opp_gta, opp_turnover, opp_orb, opp_drb, opp_trb, opp_ft, opp_ft_att, opp_pf, quote_ident(team_name) as team_name, quote_ident(opp_name) as opp_name, case when home = 'Y' then 1 else 0 end as home, dow, team_elo, team_last_game, team_score, team_game_score, opp_score, opp_elo, opp_last_game, opp_game_score, quote_ident(team_conference) as team_conference,quote_ident(opp_conference) as opp_conference
FROM elo_player_sum where date_game is not null;

create table ml_basketball_full as
SELECT player_name, gs, mp, fg, fga, fg_pct, game_three_made, game_three_att, game_three_perc, ft, fta, ft_pct, orb, drb, trb, ast, stl, blk, tov, pf, pts, game_score, plus_minus, season, date_game, game_result, team_age, team_fg, team_fga, team_gtm, team_gta, team_turnovers, team_orb, team_drb, team_trb, team_ft, team_ft_att, team_pf, opp_age, opp_fg, opp_fga, opp_gtm, opp_gta, opp_turnover, opp_orb, opp_drb, opp_trb, opp_ft, opp_ft_att, opp_pf, team_name, opp_name, home, dow, team_elo, team_last_game, team_score, team_game_score, opp_score, opp_elo, opp_last_game, opp_game_score, team_conference, opp_conference
FROM elo_player_sum where date_game is not null
UNION
SELECT player_name, NULL AS gs, NULL AS mp, NULL AS fg, NULL AS fga, NULL AS fg_pct, NULL AS game_three_made, NULL AS game_three_att, NULL AS game_three_perc, NULL AS ft, NULL AS fta, NULL AS ft_pct, NULL AS orb, NULL AS drb, NULL AS trb, NULL AS ast, NULL AS stl, NULL AS blk, NULL AS tov, NULL AS pf, NULL AS pts, NULL AS game_score, NULL AS plus_minus, NULL AS season,game_date, NULL AS game_result, NULL AS team_age, NULL AS team_fg, NULL AS team_fga, NULL AS team_gtm, NULL AS team_gta, NULL AS team_turnovers, NULL AS team_orb, NULL AS team_drb, NULL AS team_trb, NULL AS team_ft, NULL AS team_ft_att, NULL AS team_pf, NULL AS opp_age, NULL AS opp_fg, NULL AS opp_fga, NULL AS opp_gtm, NULL AS opp_gta, NULL AS opp_turnover, NULL AS opp_orb, NULL AS opp_drb, NULL AS opp_trb, NULL AS opp_ft, NULL AS opp_ft_att, NULL AS opp_pf,team as team_name,opponent as opp_name,case when (home is TRUE) then 'Y' else 'N' end as home, extract (isodow from game_date) as dow, (select "Elo" from elo_score_table where "Team" = team and "Date" = current_date) as team_elo,(select last_team_game from elo_score_table where "Team" = team and "Date" = current_date) as team_last_game,NULL as team_score,NULL as team_game_score, NULL AS opp_score,(select "Elo" from elo_score_table where "Team" = opponent and "Date" = current_date) as opp_elo, (select last_team_game from elo_score_table where "Team" = opponent and "Date" = current_date) as opp_last_game, NULL AS opp_game_score,(select conference from nba_conference where team = b.team) as team_conference, (select conference from nba_conference where team = opponent) as opp_conference
FROM game_matchup b where game_date = current_date;
create table ml_basketball_predict as
select * from ml_basketball_full where date_game = current_date;

